test fixxes
Signed-off-by: Hemankita Perabathini <phemankita@gmail.com>

diff --git a/mq/environments/ci/tasks/10-gitops-for-mq.yaml b/mq/environments/ci/tasks/10-gitops-for-mq.yaml
--- a/mq/environments/ci/tasks/10-gitops-for-mq.yaml
+++ b/mq/environments/ci/tasks/10-gitops-for-mq.yaml
@@ -89,6 +89,85 @@ spec:
         set -x
         cd $(params.source-dir)
         git checkout $(params.git-revision)
+    - name: replace-image
+      image: $(params.tools-image)
+      workingDir: $(params.source-dir)
+      env:
+        - name: TLS_SECRET_NAME
+          valueFrom:
+            configMapKeyRef:
+              name: ibmcloud-config
+              key: TLS_SECRET_NAME
+              optional: true
+        - name: INGRESS_SUBDOMAIN
+          valueFrom:
+            configMapKeyRef:
+              name: ibmcloud-config
+              key: INGRESS_SUBDOMAIN
+              optional: true
+      script: |
+          #!/usr/bin/env bash
+          set -ex
+          GIT_URL="$(params.git-url)"
+          GIT_REVISION="$(params.git-revision)"
+          APP_NAME="$(params.app-name)"
+          IMAGE_SERVER="$(params.image-server)"
+          IMAGE_NAMESPACE="$(params.image-namespace)"
+          IMAGE_REPOSITORY="$(params.image-repository)"
+          IMAGE_URL="${IMAGE_SERVER}/${IMAGE_NAMESPACE}/${IMAGE_REPOSITORY}"
+          IMAGE_VERSION="$(params.image-tag)"
+
+          if [[ $APP_NAME == *"qm"* ]] ; then
+            if [[ "$(params.ha)" == "true" ]] ; then
+              export YAML_ROOT="$(params.yaml)/native-ha-qmgr"
+            elif [[ "$(params.storage)" == "true" ]]; then
+              eport YAML_ROOT="$(params.yaml)/durable-qmgr"
+            else
+              export YAML_ROOT="$(params.yaml)/generic-qmgr"
+            fi
+          else
+            export YAML_ROOT="$(params.yaml)"
+          fi
+
+          echo "YAML_ROOT: $YAML_ROOT"
+
+          if [[ -f "$YAML_ROOT/queuemanager.yaml" ]]; then
+            export YAML="$YAML_ROOT/queuemanager.yaml"
+          elif [[ -f "$YAML_ROOT/deployment.yaml" ]]; then
+            export YAML="$YAML_ROOT/deployment.yaml"
+          elif [[ -f statefulset.yaml ]]; then
+            export YAML="$YAML_ROOT/statefulset.yaml"
+          else
+            echo "Error: No deployment file is detected"
+            exit 1
+          fi
+
+          echo "YAML: $YAML"
+          export YAML_NEW="./$YAML-new.yaml"
+          echo "YAML_NEW: $YAML_NEW"
+
+          PREFIX=""
+          if [[ -f "${YAML}" ]]; then
+            sed "/image/ s|replace|${IMAGE_URL}:${IMAGE_VERSION}|g" $YAML > $YAML_NEW
+            rm ${YAML}
+            mv ${YAML_NEW} ${YAML}
+          fi
+
+          kustomize build ./$YAML_ROOT/ > release.yaml
+
+          awk '
+          /apiVersion:/{
+            close(file)
+            file="queuemanager.yaml"
+          }
+          file!="" && !/^--/{
+            print > (file)
+          }
+          ' release.yaml
+
+          cat ./queuemanager.yaml
+      securityContext:
+        privileged: true
     - name: gitops
       image: $(params.tools-image)
       workingDir: $(params.source-dir)
@@ -150,66 +229,7 @@ spec:
       script: |
           #!/usr/bin/env bash
           set -ex
-
-          GIT_URL="$(params.git-url)"
-          GIT_REVISION="$(params.git-revision)"
           APP_NAME="$(params.app-name)"
-          IMAGE_SERVER="$(params.image-server)"
-          IMAGE_NAMESPACE="$(params.image-namespace)"
-          IMAGE_REPOSITORY="$(params.image-repository)"
-          IMAGE_URL="${IMAGE_SERVER}/${IMAGE_NAMESPACE}/${IMAGE_REPOSITORY}"
-          IMAGE_VERSION="$(params.image-tag)"
-
-          if [[ $APP_NAME == *"qm"* ]] ; then
-            if [[ "$(params.ha)" == "true" ]] ; then
-              export YAML_ROOT="$(params.yaml)/native-ha-qmgr"
-            elif [[ "$(params.storage)" == "true" ]]; then
-              export YAML_ROOT="$(params.yaml)/durable-qmgr"
-            else
-              export YAML_ROOT="$(params.yaml)/generic-qmgr"
-            fi
-          else
-            export YAML_ROOT="$(params.yaml)"
-          fi
-
-          echo "YAML_ROOT: $YAML_ROOT"
-
-          if [[ -f "$YAML_ROOT/queuemanager.yaml" ]]; then
-            export YAML="$(params.yaml)/generic-qmgr/queuemanager.yaml"
-          elif [[ -f "$YAML_ROOT/deployment.yaml" ]]; then
-            export YAML="$YAML_ROOT/deployment.yaml"
-          elif [[ -f statefulset.yaml ]]; then
-            export YAML="$YAML_ROOT/statefulset.yaml"
-          else
-            echo "Error: No deployment file is detected"
-            exit 1
-          fi
-
-          echo "YAML: $YAML"
-          export YAML_NEW="./$YAML-new.yaml"
-          echo "YAML_NEW: $YAML_NEW"
-
-          PREFIX=""
-          if [[ -f "${YAML}" ]]; then
-            sed "/image/ s|replace|${IMAGE_URL}:${IMAGE_VERSION}|g" $YAML > $YAML_NEW
-            rm ${YAML}
-            mv ${YAML_NEW} ${YAML}
-          fi
-
-          kustomize build ./$YAML_ROOT/ > release.yaml
-
-          awk '
-          /apiVersion:/{
-            close(file)
-            file="queuemanager.yaml"
-          }
-          file!="" && !/^--/{
-            print > (file)
-          }
-          ' release.yaml
-
-          cat ./queuemanager.yaml
-
           SUBDIR="$(params.subdir)"
           if [[ -z "${SUBDIR}" ]]; then
             SUBDIR="${APP_NAME}"
@@ -255,7 +275,7 @@ spec:
             export SOURCE_DIR="../$(params.yaml)"
           fi
           if [[ -f "$(params.source-dir)/queuemanager.yaml" ]]; then
-            cp $(params.source-dir)/queuemanager.yaml $(params.app-path)/$(params.environment)/${SUBDIR}/queuemanager
+            cp -r $(params.source-dir)/queuemanager.yaml $(params.app-path)/$(params.environment)/${SUBDIR}/queuemanager
           elif [[ -f "$SOURCE_DIR/deployment.yaml" ]]; then
             cp -r "$SOURCE_DIR"/deployment.yaml $(params.app-path)/$(params.environment)/${SUBDIR}/deployment
           elif [[ -f statefulset.yaml ]]; then
@@ -298,5 +318,214 @@ spec:
             GIT_PUSH_URL="${PROTOCOL}://api.github.com/repos/${GIT_ORG}/${GIT_REPO}/pulls"
             curl -u ${GIT_AUTH_USER}:${GIT_AUTH_PWD} -d '{"title":"PR to promote to '$(params.dest-environment)' for '$(params.app-name)'","base":"'${GIT_BRANCH}'", "head":"'${GIT_ORG}':cntk-ci-pipeline-'${APP_NAME}'-'${APP_VERSION}'"}' ${GIT_PUSH_URL}
           fi
-      securityContext:
-        privileged: true
+    # - name: gitops
+    #   image: $(params.tools-image)
+    #   workingDir: $(params.source-dir)
+    #   env:
+    #     - name: NAMESPACE
+    #       valueFrom:
+    #         fieldRef:
+    #           fieldPath: metadata.namespace
+    #     - name: HOME
+    #       value: /home/devops
+    #     - name: GIT_USERNAME
+    #       valueFrom:
+    #         secretKeyRef:
+    #           name: git-credentials
+    #           key: username
+    #           optional: true
+    #     - name: GIT_PASSWORD
+    #       valueFrom:
+    #         secretKeyRef:
+    #           name: git-credentials
+    #           key: password
+    #           optional: true
+    #     - name: GIT_PARENT_DIR
+    #       valueFrom:
+    #         configMapKeyRef:
+    #           name: gitops-repo
+    #           key: parentdir
+    #           optional: true
+    #     - name: GIT_PROTOCOL
+    #       valueFrom:
+    #         configMapKeyRef:
+    #           name: gitops-repo
+    #           key: protocol
+    #           optional: true
+    #     - name: GIT_HOST
+    #       valueFrom:
+    #         configMapKeyRef:
+    #           name: gitops-repo
+    #           key: host
+    #           optional: true
+    #     - name: GIT_ORG
+    #       valueFrom:
+    #         configMapKeyRef:
+    #           name: gitops-repo
+    #           key: org
+    #           optional: true
+    #     - name: GIT_REPO
+    #       valueFrom:
+    #         configMapKeyRef:
+    #           name: gitops-repo
+    #           key: repo
+    #           optional: true
+    #     - name: GIT_BRANCH
+    #       valueFrom:
+    #         configMapKeyRef:
+    #           name: gitops-repo
+    #           key: branch
+    #           optional: true
+    #   script: |
+    #       #!/usr/bin/env bash
+    #       set -ex
+    #
+    #       GIT_URL="$(params.git-url)"
+    #       GIT_REVISION="$(params.git-revision)"
+    #       APP_NAME="$(params.app-name)"
+    #       IMAGE_SERVER="$(params.image-server)"
+    #       IMAGE_NAMESPACE="$(params.image-namespace)"
+    #       IMAGE_REPOSITORY="$(params.image-repository)"
+    #       IMAGE_URL="${IMAGE_SERVER}/${IMAGE_NAMESPACE}/${IMAGE_REPOSITORY}"
+    #       IMAGE_VERSION="$(params.image-tag)"
+    #
+    #       if [[ $APP_NAME == *"qm"* ]] ; then
+    #         if [[ "$(params.ha)" == "true" ]] ; then
+    #           export YAML_ROOT="$(params.yaml)/native-ha-qmgr"
+    #         elif [[ "$(params.storage)" == "true" ]]; then
+    #           export YAML_ROOT="$(params.yaml)/durable-qmgr"
+    #         else
+    #           export YAML_ROOT="$(params.yaml)/generic-qmgr"
+    #         fi
+    #       else
+    #         export YAML_ROOT="$(params.yaml)"
+    #       fi
+    #
+    #       echo "YAML_ROOT: $YAML_ROOT"
+    #
+    #       if [[ -f "$YAML_ROOT/queuemanager.yaml" ]]; then
+    #         export YAML="$(params.yaml)/generic-qmgr/queuemanager.yaml"
+    #       elif [[ -f "$YAML_ROOT/deployment.yaml" ]]; then
+    #         export YAML="$YAML_ROOT/deployment.yaml"
+    #       elif [[ -f statefulset.yaml ]]; then
+    #         export YAML="$YAML_ROOT/statefulset.yaml"
+    #       else
+    #         echo "Error: No deployment file is detected"
+    #         exit 1
+    #       fi
+    #
+    #       echo "YAML: $YAML"
+    #       export YAML_NEW="./$YAML-new.yaml"
+    #       echo "YAML_NEW: $YAML_NEW"
+    #
+    #       PREFIX=""
+    #       if [[ -f "${YAML}" ]]; then
+    #         sed "/image/ s|replace|${IMAGE_URL}:${IMAGE_VERSION}|g" $YAML > $YAML_NEW
+    #         rm ${YAML}
+    #         mv ${YAML_NEW} ${YAML}
+    #       fi
+    #
+    #       kustomize build ./$YAML_ROOT/ > release.yaml
+    #
+    #       awk '
+    #       /apiVersion:/{
+    #         close(file)
+    #         file="queuemanager.yaml"
+    #       }
+    #       file!="" && !/^--/{
+    #         print > (file)
+    #       }
+    #       ' release.yaml
+    #
+    #       cat ./queuemanager.yaml
+    #
+    #       SUBDIR="$(params.subdir)"
+    #       if [[ -z "${SUBDIR}" ]]; then
+    #         SUBDIR="${APP_NAME}"
+    #       fi
+    #       PROTOCOL="${GIT_PROTOCOL}"
+    #       if [[ -z "${PROTOCOL}" ]]; then
+    #         PROTOCOL="https"
+    #       fi
+    #       if [[ -z "${GIT_HOST}" ]] || [[ -z "${GIT_ORG}" ]] || [[ -z "${GIT_REPO}" ]]; then
+    #           echo "GitOps repo has not been configured with confimap gitops-repo. Skipping trigger step"
+    #           exit 0
+    #       fi
+    #       set +x
+    #       if [[ -n "${GIT_USERNAME}" ]]; then
+    #         GIT_AUTH_USER="${GIT_USERNAME}"
+    #         GIT_AUTH_PWD="${GIT_PASSWORD}"
+    #       else
+    #         echo "Credentials for GitOps repo not set in secret gitops-cd-secret or git-credentials"
+    #         exit 1
+    #       fi
+    #       set -x
+    #       BRANCH_CMD=""
+    #       if [[ -n "${GIT_BRANCH}" ]]; then
+    #         BRANCH_CMD="-b ${GIT_BRANCH}"
+    #       fi
+    #       git config --global user.email "gitops@cloudnativetoolkit.dev"
+    #       git config --global user.name "Cloud Native Toolkit Pipeline"
+    #       echo "git clone ${BRANCH_CMD} ${PROTOCOL}://${GIT_AUTH_USER}:xxxx@${GIT_HOST}/${GIT_ORG}/${GIT_REPO}"
+    #       set +x
+    #       GIT_URL="${PROTOCOL}://${GIT_AUTH_USER}:${GIT_AUTH_PWD}@${GIT_HOST}/${GIT_ORG}/${GIT_REPO}"
+    #       git clone ${BRANCH_CMD} ${GIT_URL} gitops_cd
+    #       set -x
+    #       cd gitops_cd
+    #       if [[ $APP_NAME == *"qm"* ]]; then
+    #         if [[ "$(params.ha)" == "true" ]] ; then
+    #           export SOURCE_DIR="../$(params.yaml)/native-ha-qmgr"
+    #         elif [[ "$(params.storage)" == "true" ]]; then
+    #           export SOURCE_DIR="../$(params.yaml)/durable-qmgr"
+    #         else
+    #           export SOURCE_DIR="../$(params.yaml)/generic-qmgr"
+    #         fi
+    #       else
+    #         export SOURCE_DIR="../$(params.yaml)"
+    #       fi
+    #       if [[ -f "$(params.source-dir)/queuemanager.yaml" ]]; then
+    #         cp $(params.source-dir)/queuemanager.yaml $(params.app-path)/$(params.environment)/${SUBDIR}/queuemanager
+    #       elif [[ -f "$SOURCE_DIR/deployment.yaml" ]]; then
+    #         cp -r "$SOURCE_DIR"/deployment.yaml $(params.app-path)/$(params.environment)/${SUBDIR}/deployment
+    #       elif [[ -f statefulset.yaml ]]; then
+    #         cp -r "$SOURCE_DIR"/statefulset.yaml $(params.app-path)/$(params.environment)/${SUBDIR}/deployment
+    #       else
+    #         echo "No change in deployment file"
+    #       fi
+    #
+    #       if ls $SOURCE_DIR/*.mqsc &> /dev/null; then
+    #         cp -r "$SOURCE_DIR"/*.mqsc $(params.app-path)/$(params.environment)/"${SUBDIR}"/configmap
+    #       fi
+    #
+    #       if ls $SOURCE_DIR/*.ini &> /dev/null; then
+    #         cp -r "$SOURCE_DIR"/*.ini $(params.app-path)/$(params.environment)/"${SUBDIR}"/configmap
+    #       fi
+    #
+    #       if ls $SOURCE_DIR/configmap*.yaml &> /dev/null; then
+    #         cp -r "$SOURCE_DIR"/configmap*.yaml $(params.app-path)/$(params.environment)/"${SUBDIR}"/configmap
+    #       fi
+    #
+    #       if ls $SOURCE_DIR/*secret*.yaml &> /dev/null; then
+    #         cp -r "$SOURCE_DIR"/*secret*.yaml $(params.app-path)/$(params.environment)/"${SUBDIR}"/secrets
+    #       fi
+    #
+    #       APP_VERSION="$(git rev-parse HEAD | cut -c 1-8)"
+    #       if [[ $(git status -s | wc -l) -eq 0 ]]; then
+    #         echo "No changes"
+    #         exit 0
+    #       elif [[ "$(params.git-pr)" = "false" ]]; then
+    #         git add .
+    #         git commit -m "Updates ${APP_NAME} to ${VERSION}"
+    #         git push -v
+    #       else
+    #         git checkout -b cntk-ci-pipeline-${APP_NAME}-${APP_VERSION}
+    #         # push changes to git
+    #         git status
+    #         git add "${SUBDIR_DEST}/"
+    #         git commit -m "Cloudnative toolkit pipeline updates ${APP_NAME}" --no-edit --signoff
+    #         git push origin cntk-ci-pipeline-${APP_NAME}-${APP_VERSION}
+    #         GIT_PUSH_URL="${PROTOCOL}://api.github.com/repos/${GIT_ORG}/${GIT_REPO}/pulls"
+    #         curl -u ${GIT_AUTH_USER}:${GIT_AUTH_PWD} -d '{"title":"PR to promote to '$(params.dest-environment)' for '$(params.app-name)'","base":"'${GIT_BRANCH}'", "head":"'${GIT_ORG}':cntk-ci-pipeline-'${APP_NAME}'-'${APP_VERSION}'"}' ${GIT_PUSH_URL}
+    #       fi
+    #   securityContext:
+    #     privileged: true
